sudo: required

services:
    - docker

env:
    CONTAINER='centos:latest'
    IMG_TARBALL='centos4.tar.xz'

before_install:
    - docker pull carlad/sinatra
    - docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
    - docker ps -a
    - docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"
    - docker pull ${CONTAINER}

script:
    - docker run --privileged -i -t -v ${PWD}:/srv -e "IMG_TARBALL=${IMG_TARBALL}" ${CONTAINER} /srv/build.sh
    - |
      cat <<EOF > Dockerfile
      FROM scratch
      MAINTAINER pigfoot <pigfoot@gmail.com>
      ADD /${IMG_TARBALL} /
      CMD ["/bin/bash"]
      EOF
    - docker build -t pigfoot/centos:4 .
    - docker push pigfoot/centos:4
